### ISSUE TITLE
Combos are not properly sorted by length when triggered

### ISSUE THREAD

**Issue by normanrz** [RobertWHurst/KeyboardJS#100]
I added `space` and then `shift + space` as key bindings. Now, if I press `shift + space` only the `space` handler is called. When I swap the bindings it works correctly. Is this intended behavior?

**Comment by RobertWHurst** [comment]
No this seems to be a bug. The library is suppose to sort key combos by length. Longer combos should always trigger first.

**Comment by RobertWHurst** [comment]
I believe this is fixed
