### ISSUE TITLE
keyboard cheat sheet and cross platform shortcuts trigger

### ISSUE THREAD

**Issue by Huxpro** [RobertWHurst/KeyboardJS#104]
Well, It is not that matter that there is not a cheat sheet of all keyboard modifiers you are using, but It is better to have one. People like me will try things like `cmd + i` or `⌘ + i` and fail.

In addition. Sort of cross platform shortcuts trigger is very helpful, like the one mousetrap supported;

**Comment by RobertWHurst** [comment]
There is sort of a cheatsheet. Have a look at the source for the US locale. There you will find all of the key aliases you are looking for. => https://github.com/RobertWHurst/KeyboardJS/blob/master/locales/us.js
