### ISSUE TITLE
How to use watch function?

### ISSUE THREAD

**Issue by Altiano** [RobertWHurst/KeyboardJS#111]
I think that `watch()` wll scope the event if the user set the focus on something (click the element/window area) .

this is index.js:
`  keyboardJS.watch(document.querySelector('.a'))

    keyboardJS.bind('a', function(e) {
      console.log('a is pressed');
    });
`
this is my index.html:
`<div class="a"></div>
<div class="b"></div>`

what i'm trying to do is to only fire the event if user click on `a`.
those code won't work as I'm expecting

**Comment by RobertWHurst** [comment]
KeyboardJS does not handle click events. It's for use with keyboard input.
