### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by jhm-ciberman** [RobertWHurst/KeyboardJS#112]
I have a desktop app written in javascript with multiple windows. 
when I do:
```
KeyboardJS.watch(window1); 
KeyboardJS.watch(window2); 
KeyboardJS.watch(window3);
```
Only the last window is watched. 
Any help is appreciated. Thanks.

**Comment by RobertWHurst** [comment]
This is expected behaviour. `watch` calls `stop` which unbinds the previous window. This is to prevent unexpected behaviour. My suggestion would be to centralize your event handling, or switch windows by using the `focus` event.
