### ISSUE TITLE
Combos with repetition of the same character breaks the other listeners.

### ISSUE THREAD

**Issue by abuduba** [RobertWHurst/KeyboardJS#117]
Having some key combinations:

```
keyboardJS.bind('1+1', () => console.log('11'));
keyboardJS.bind('1+2', () => console.log('12'));
keyboardJS.bind('1+3', () => console.log('13'));
```

It's not possible to handle neither 12 nor 13 due to 11 executes its callback on the first click on "1".

It's pretty much the same like in the other hotkey plugin: https://github.com/dmauro/Keypress/issues/120

**Comment by RobertWHurst** [comment]
Perhaps this should raise an exception. You shouldn't be able to bind 1+1.

**Comment by abuduba** [comment]
Hi, Thanks for the reply and sorry for the delay.
There was some misunderstanding from my side.
Sorry for confusion.
I thought the lib supports key sequences, so i can for example react on combination "11" by pressing on "1", release it and press again the same key, or some other case like trigger some action when user puts some "secret" word or something like that.

Suppose the "bug" might be closed.
BTW, do you have in plan supporting the sequences like that?

**Comment by RobertWHurst** [comment]
@abuduba No worries. I do, but I haven't had time to work on it as of late. I'll let you know if this feature is added 🍻
