### ISSUE TITLE
What do you mean by scope?

### ISSUE THREAD

**Issue by timwis** [RobertWHurst/KeyboardJS#123]
Hey, cool library! I've gotta be honest, I have no idea what you mean by scope. I would have assumed it had something to do with, "i only care about keyboard events when this element is focused on," but I have a feeling that's not what it is.

**Comment by RobertWHurst** [comment]
What I mean by scope is the ability to constrain bindings to select areas of your application. So, for example, the bindings for your landing page may be different than the bindings for your settings page. This can be achieved with the setContext() method.
