### ISSUE TITLE
"Meta" key support

### ISSUE THREAD

**Issue by daytonlowell** [RobertWHurst/KeyboardJS#128]
Would be nice to be able to do `keyboardJS.bind('meta', function(e) {})` and have KeyboardJS figure would out the correct key to bind based on the platform. On Windows and Linux it would be `ctrl` and on macOS it would be both `leftcommand` and `rightcommand`.

**Comment by RobertWHurst** [comment]
I agree this would be nice. I could be added to the US local as a macro.
