### ISSUE TITLE
Command + shift + r keyup not working

### ISSUE THREAD

**Issue by vinothwindows47** [RobertWHurst/KeyboardJS#132]

**Comment by RobertWHurst** [comment]
Can you please provide your version of KeyboardJS, your OS, and your browser?

**Comment by RobertWHurst** [comment]
Closing due to lack of info.

**Comment by vinothwindows47** [comment]
KeyboardJS version : 2.1.1

OS : Macbook pro

browser: chrome

**Comment by RobertWHurst** [comment]
It's been some time since this issue was posted but I'd still like to look into it.

This is likely due to the browser or OS taking control away from the browser. Mind sharing an example of your code?

**Comment by RobertWHurst** [comment]
So this should be fixed in the current version of keyboardJS. I've tested on the latest macOS with chrome. Let me know if you are still having an issue should you try the new version.
