### ISSUE TITLE
Pressing any key while holding the binded key triggers the keydown handler again

### ISSUE THREAD

**Issue by jean-emmanuel** [RobertWHurst/KeyboardJS#133]
It only happens when `preventRepeat()` is not called in the callback function. 

Tested with Chromium 62 under gnu/linux debian testing.

edit: thanks for the great lib ;)

**Comment by jean-emmanuel** [comment]
Here is a minimal setup to reproduce the issue:
```js
keyboardJS.bind('a', function(e) {
  console.log('a is pressed');
});
```
- press and hold `a`
- press any other key while holding `a`

**Comment by RobertWHurst** [comment]
Thanks for the information. I appreciate the effort. I'll have a look into it.
Happy new year!

**Comment by jean-emmanuel** [comment]
Cheers :+1:

**Comment by RobertWHurst** [comment]
I'm back from the void, sorry for taking so long.

I'm going to leave this behavior intact for the moment. If you haven't called preventRepeat then it should be expected that your callback will have called over and over again anyway. Is there a particular problem you where dealing with when you tried to fix this? I'd be interested in seeing what you were trying to resolve.

**Comment by jean-emmanuel** [comment]
If I remember correctly the issue was particulary problematic when the other key was bound too. I don't think the behavior is expected, try holding a key in a text editor and then press another key: the keyrepeat loop stops and the other behaves normally.

**Comment by RobertWHurst** [comment]
@jean-emmanuel I just published version 2.6.3 which includes a change to prevent repeat once a non-combo key is pressed. It's similar to your change, but I ended up making some changes to the locale for tracking the last pressed key. If you've got the time check it out and let me know what you think.

**Comment by jean-emmanuel** [comment]
Thanks, I'll test this soon and let you know !

**Comment by jean-emmanuel** [comment]
Looks good to me :)

**Comment by RobertWHurst** [comment]
That's good to hear. Thanks @jean-emmanuel 🍻
