### ISSUE TITLE
Event triggers without the binding in windows

### ISSUE THREAD

**Issue by light94** [RobertWHurst/KeyboardJS#139]
Hi,
I have the following code (also demo app available [here](https://light94.github.io/keyboardjsdemo/))
```
<head>
    <script type="text/javascript" src="https://rawgit.com/RobertWHurst/KeyboardJS/master/dist/keyboard.min.js"></script>
    <script>
        keyboardJS.bind('menu + r', function(e){e.preventDefault(); console.log('trigerred menu + r')})
    </script>
</head>

```
It does not behave as expected in Windows on Firefox browser, where sometimes it does not bind, and when it does, then after executing once, it triggers without pressing the menu key. It happens sometime in Chrome as well, although I have not been able to consistently reproduce there.
Works fine in Mac (firefox and chrome)

Any pointers on what the issue might be would be very helpful.

**Comment by RobertWHurst** [comment]
I believe this might be an OS or browser quirk around the menu key, but I will have a look 👍

**Comment by RobertWHurst** [comment]
I gave it a shot on windows using Firefox and Chrome. It seems preventDefault doesn't seem to stop the OS/browser from taking over and showing the menu, so there's not much I can do to fix this. That said if anyone manages a fix please update this thread and we'll see if we can fix it.
