### ISSUE TITLE
What is the desired behavior of preventRepeat?

### ISSUE THREAD

**Issue by ianshade** [RobertWHurst/KeyboardJS#142]
I used the exact sample called "Prevent keydown repeat" from Readme. Results I'm getting: after pressing the A key, "a is pressed" is printed once. Holding the key doesn't result in printing it more times - correct. But after releasing the key and pressing it again, nothing is printed - so the combo works in fact only once. Is it correct behavior or should it trigger again after releasing the key and pressing it again?

**Comment by boldenburg** [comment]
@ianshade this seems to be a bug, you can get the behavior you want by passing an empty releaseHandler to bind()

```javascript
keyboardJS.bind('escape', function(e) {
	e.preventRepeat();
	console.log("pressed escape");
}, function(e) {
	
});
```

**Comment by pycraft114** [comment]
@boldenburg Wouldn't it be better not to pass unnecessary releaseHandler?

**Comment by boldenburg** [comment]
Unfortunately it's the nature of bugs to force us into what appears to be unnecessary behavior.

**Comment by andrewstart** [comment]
A bug in same theme: the `preventRepeatByDefault` parameter seems to block the press callback altogether, so manually calling `preventRepeat()` and supplying a no-op release handler is the only way to go.

**Comment by RobertWHurst** [comment]
Hmm, this is a crappy bug. Looking into it.

**Comment by RobertWHurst** [comment]
This should be fixed now. I added a test case as well. Let me know if things are working for you now. If not please follow up and I'll have another look 👍
