### ISSUE TITLE
For what reason might numeric keypad not work?

### ISSUE THREAD

**Issue by mspreij** [RobertWHurst/KeyboardJS#143]
I have one handler set up as:

    keyboardJS.bind(['1','2','3','4','5','6','7','8','9','0'], function(e) {..

but it only works for the numbers row, not the numeric keypad.
Typing numbers with the keypad works fine.
This is on Windows 10 which I'm not exactly an expert in, is there a keyboard layout issue I could check?

**Comment by Pytness** [comment]
The keywords are defined here: [us.js](https://github.com/RobertWHurst/KeyboardJS/blob/master/locales/us.js)

In the line 55 u can read:
`  locale.bindKeyCode(96, ['numzero', 'num0']);`

You need to prepend 'num' on each number.

**Comment by mspreij** [comment]
I'll try that tomorrow. Funnily it works as-is on mac, so I thought it might be a windows issue..

**Comment by RobertWHurst** [comment]
@Pytness is correct. Closing for now, but update us if you want to follow up on this issue more.
