### ISSUE TITLE
HOW TO CREATE WITH A JAPANESE LOCALE?

### ISSUE THREAD

**Issue by ervishal89** [RobertWHurst/KeyboardJS#146]
Hi,

I am exploring KeyboardJs, could you please let me know how to make this work with other locale like Japanese?

**Comment by RobertWHurst** [comment]
I'd love it if you'd like to contribute a Japanese locale, that said in the near future I'll be switching KeyboardJS to use the newer code property on keyboard events and getting rid of the use of keycodes.

If you still are interested in giving it a shot, have a look at locales/us.js. you'd need to create a locales/jp.js and register it in index.js.

Closing for now, but please follow up if you wish.
