### ISSUE TITLE
Can't bind on a combo that includes a delimiter

### ISSUE THREAD

**Issue by daytonlowell** [RobertWHurst/KeyboardJS#147]
```js
keyboardJS.bind('mod + +', event => {
	//
})
```

This won't fire as one might expect because `+` is the delimiter. I assume the same issue would occur for `'mod > >'`. Is there a work around? Should I make try to make the `KeyCombo._splitStr` method in `key-combo.js` smarter and make a PR?

**Comment by daytonlowell** [comment]
Anyone have any ideas?

**Comment by tannerlyons** [comment]
This works:
```
keyboardJS.bind("ctrl + \\+", function() {
  console.log("oh yeah escape chars!");
});
```

**Comment by RobertWHurst** [comment]
@tannerlyons is correct.

If you like you can also use the alias for `+`, `plus`.
```
keyboardJS.bind("ctrl + plus", function() {
  // aliases work too
});
```
