### ISSUE TITLE
Press key on electron

### ISSUE THREAD

**Issue by artmadeit** [RobertWHurst/KeyboardJS#148]
I made a simple test using electron (the quickstart electron) and at key bindings using this library are working but keypress not. So my question is, does this library support keypress in electron?
like:
```javascript
keyboardJS.bind('shift + f2', () => {
  keyboardJS.pressKey('a');
});
```

Currenlty bindings work well but not the pressKey

**Comment by RobertWHurst** [comment]
Interesting. I haven't tested with electron yet, but I'll have a look. Not sure why it wouldn't work.

**Comment by RobertWHurst** [comment]
Looks like calling pressKey in a handler was causing an infinate loop. I pushed a fix, so it should be working now. Please feel free to follow up if you still have issue after upgrading.
