### ISSUE TITLE
bind() with preventRepeatByDefault=true omits the first firing of pressHandler

### ISSUE THREAD

**Issue by jonathanwin** [RobertWHurst/KeyboardJS#159]
With preventRepeatByDefault=true, the first time the combo is pressed and released, only the releaseHandler is fired

**Example code**
```js
keyboardJS.bind('c',
  () => console.log('pressed c'),
  () => console.log('released c'),
  true)
```
https://jsfiddle.net/nzao3bdc/5/

**Result**
press and release "c" :
> "released c"

press and release "c" again :
> "pressed c"
> "released c"

**Expected behavior**
press and release "c" :
> "pressed c"
> "released c"

press and release "c" again :
> "pressed c"
> "released c"

**Enviroment:**
 - OS: Linux
 - Browser Chrome 83 , Firefox ESR 
 - KeyboardJS version: 2.6.2, master (970e19a2)

**Proposed fix**
It looks like the problem is here: https://github.com/RobertWHurst/KeyboardJS/blob/master/lib/keyboard.js#L86
```js
    this._listeners.push({
      keyCombo              : keyComboStr ? new KeyCombo(keyComboStr) : null,
      pressHandler          : pressHandler           || null,
      releaseHandler        : releaseHandler         || null,
// bug here? :
      preventRepeat         : preventRepeatByDefault || false, // should be just false
      preventRepeatByDefault: preventRepeatByDefault || false,
      executingHandler      : false
    });
```

**Comment by RobertWHurst** [comment]
Thanks for reporting. I'll have a look.

**Comment by utiq** [comment]
I'm experiencing the same issue, is this going to be resolved?

**Comment by RobertWHurst** [comment]
It should be resolved now in the latest build
