### ISSUE TITLE
ES6 is a breaking change

### ISSUE THREAD

**Issue by narkowicz** [RobertWHurst/KeyboardJS#161]
**Describe the bug**

Updating from `2.5.1` to `2.6.3` introduces ES6 code to the `main` module import. While this isn't an API change this does break existing code, which is unexpected for a minor version update.

**Example code**

Our setup is quite typical in that we use TypeScript / Babel for compiling our own code but do not compile `node_modules`, with the exception of specific modules that require compiling for a given build target (where those modules don't ship with support for those targets).

Our ES6 imports are compiled to `require('keyboardjs')`, which breaks in our `jsdom` test environment (using `ts-jest`) since the `main` module imports for `keyboardjs` now include ES6 code (such as `import` and `class`).

**Expected behavior**

Module environment compatibility should remain / be backwards compatible between minor version updates.

**Environment**

- macOS
- `jsdom` via `jest`

**Comments**

There are workarounds, though not without drawbacks:
- Importing directly from `keyboardjs/dist/keyboard.js` (though this breaks compatibility with `@types/keyboardjs`)
- Update configuration to compile `keyboardjs` for test and production environments wherever necessary

**Proposed fix**

Update `main` in `package.json` to point to the compiled code in `dist/keyboard.js` so that the main module import remains compatible with previous versions of `2.x.x` (and release as a hot-fix).

**Comment by RobertWHurst** [comment]
Thanks for reporting this. Yeah, this is something that needs to be fixed. I'll sort it and push a release.

**Comment by RobertWHurst** [comment]
Since this was an unindended bug, I've released a new patch version 2.6.4. This should be resolved now.
