### ISSUE TITLE
Error when starting the program

### ISSUE THREAD

**Issue by FahrulID** [RobertWHurst/KeyboardJS#165]
`C:\Users\fahru\OneDrive\Desktop\Project\non-fullsize-keyboard-keymapping\node_modules\keyboardJS\dist\keyboard.js:614
            throw new Error('Cannot find window functions addEventListener or attachEvent.');`

It's showing this error when running it, even with the simplest code :

`const keyboardJS = require('keyboardJS');

keyboardJS.on("n", function () {alert("n pressed");});
`

`
const keyboardJS = require('keyboardJS');

keyboardJS.bind('a', (e) => {
    // pressKey
    keyboardJS.pressKey('b');

    // releaseKey
    keyboardJS.releaseKey('b');
});`

**Comment by RobertWHurst** [comment]
Just a quick update there, I've updated the lib to support non browser environments removing the need to perform a work around. See commit https://github.com/RobertWHurst/KeyboardJS/commit/3ab58eb3cdcd78b57da08139babc639c1591850e
