### ISSUE TITLE
Question: is it possible to unbind browser default shortcut like Command + W / Control + W

### ISSUE THREAD

**Issue by TATOAO** [RobertWHurst/KeyboardJS#168]
Hi, I'm trying to bind Command + W / Control + W to another function. I tried:

``` js
keyboardJS.unbind("command + w");
keyboardJS.bind("command + w", (e) => {
    // some other functions
});
```

 but the browser will just close my page...
any advice will be appreciated XD
Thank you in advance

**Comment by RobertWHurst** [comment]
This is because command + w is a key binding setup by your operating system, not your browser, so the browser cannot override it. Unfortunately do don't believe there is any way around this. Best to use key combos not used by supported OSes.
