### ISSUE TITLE
Only the first binding fires when multiple are bound to the same combo

### ISSUE THREAD

**Issue by RienNeVaPlus** [RobertWHurst/KeyboardJS#58]
Hello,

i have to assign multiple events to the same key (-combos).
As seen in this Fiddle (http://jsfiddle.net/Ntbf7/5/) only the first event is called.

Is there an easy way to enable KeyboardJS to fire all observed events?

Thank you

**Comment by RobertWHurst** [comment]
This is a bug. Both should fire. I'll have a look.

**Comment by RobertWHurst** [comment]
Fixed in KeyboardJS 2
