### ISSUE TITLE
undefined variable [kI] in clear.key

### ISSUE THREAD

**Issue by hansanghoon** [RobertWHurst/KeyboardJS#60]
595:if(binding.keyCombo[kI].indexOf(keyName) > -1) {
should be
if(binding.keyCombo[cI].indexOf(keyName) > -1) {

or 

590:    var bI, cI, binding;
to
var bI, kI, binding;

**Comment by RobertWHurst** [comment]
Can't find the line your talking about, the source code, and thus the line numbers have changed.
