### ISSUE TITLE
ALT key combinations in IE-10 comapatibility mode

### ISSUE THREAD

**Issue by interface101** [RobertWHurst/KeyboardJS#61]
ALT key combinations (Alt+a.....z) doesn't work when switch to compatibility mode in IE-10.

Here is the stack trace....

SCRIPT5007: Unable to get property 'match' of undefined or null reference
keyboard.js, line 868 character 3

**Comment by RobertWHurst** [comment]
Hmm, I'mm have a look once I find a PC.

**Comment by RobertWHurst** [comment]
I don't think I want to support compat mode, seems out of scope.
