### ISSUE TITLE
Event triggers on any key after first occurrence on specified key

### ISSUE THREAD

**Issue by dandv** [RobertWHurst/KeyboardJS#76]
[JSBin](http://jsbin.com/kexovesogo/1/edit?html,output)

```html
<!doctype html>
<html lang="en-US">

<head>
<script src="https://rawgit.com/dandv/KeyboardJS/master/keyboard.js"></script>
</head>

<body>

<script>
KeyboardJS.on('k', function () {
  alert('Pressed k');
});  
</script>

</body>
</html>
```

After I press `k` and dismiss the alert in the latest Chrome, any keypress will trigger the function. This seems like a pretty big bug, so maybe I haven't read the docs correctly, or there needs to be a gotcha for this simple usage?

**Comment by RobertWHurst** [comment]
This is because the alert box took focus from the main window and the keyup event was never observed. This causes k key to remain in the active keys array. I recommend avoiding anything that steals window focus.

See http://jsbin.com/cibebomepo/1/
