### ISSUE TITLE
Preventing repeating events when key held down ?

### ISSUE THREAD

**Issue by cotejp** [RobertWHurst/KeyboardJS#79]
Is there a way to prevent repeating events from firing when a key is being held down ? I know the Keypress library has that feature but I find the API cumbersome and would rather use KeyboardJS.

**Comment by cotejp** [comment]
Hello Robert, 

I created a pull request with this option added in (preventRepeat). I also added the ability to use preventDefault straight from the same 4th options parameter.

**Comment by RobertWHurst** [comment]
Added your preventRepeat method to KeyboardJS 2
