### ISSUE TITLE
"ReferenceError: KeyboardJS is not defined" when using with AngularJS

### ISSUE THREAD

**Issue by Bambusstock** [RobertWHurst/KeyboardJS#81]
Hi,

I noticed an issue when using AngularJS and KeyboardJS together. In a project we are loading KeyboardJS dynamically after our Angular app is settled. It seems like Angular defines the global variable `module` and therefore KeyboardJS picks the `constructCommonJS` factory method. 

Checkout Line 21:
`else if(typeof module !== 'undefined') {constructCommonJS()}`

I solved the issue by commenting out the if-condition. In other cases it might be resolved by loading KeyboardJS first. However, I am not sure if this is a real issue and the condition should be improved. 

Greetings

**Comment by shuvalov-anton** [comment]
Probably, [best practice][1] is checking `exports` instead `module` in the condition:

```js
else if (typeof exports === 'object') { /* … */ }
```

[1]: https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

**Comment by Bambusstock** [comment]
Well this way it definitely works with AngularJS. I do not have a CommonJS setup to test if it works with that, though.

**Comment by RobertWHurst** [comment]
KeyboardJS 2 uses browserify to create a UMD wrapped build. The should be fixed.
