### ISSUE TITLE
Mac: Left command key only works in chrome/safari, right command key doesn't work.

### ISSUE THREAD

**Issue by itsgreggreg** [RobertWHurst/KeyboardJS#82]
Key Code is unfortunately browser and possibly operating system specific: http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript#3922353

This is preventing being able to use KeyboardJS to override shortcuts like create tab(command+t) and save file(command+s) on mac.

**Comment by itsgreggreg** [comment]
https://github.com/RobertWHurst/KeyboardJS/pull/83

**Comment by RobertWHurst** [comment]
Added fixes for this to KeyboardJS 2
