### ISSUE TITLE
IE 11 Ctrl + O always opens "Open" window

### ISSUE THREAD

**Issue by DamianS1987** [RobertWHurst/KeyboardJS#84]
e.preventDefault(); doesn't work of course. This behaviour is prevented in Chrome, Safari, FF.

From what I've noticed this might be related to this IE11 issue - https://connect.microsoft.com/IE/feedback/details/1046712/javascript-interception-and-termination-of-some-key-events-is-broken

It would be great to find a different workaround this issue than the one suggested in the link. If you can reproduce that (use the code below) please hit "Repros" button from the link above. Maybe somebody in Microsoft will handle the issue.

Here is a piece of code that I'm using:
KeyboardJS.on('ctrl + o', function(e) {
    e.preventDefault();
    console.log('ctrl o!', e);
    return false;
});

http://dstefaniak-staging.com/tests/keyboard/KeyboardJS-master/experiment.html

**Comment by RobertWHurst** [comment]
If the browser doesn't allow us to block the event, there isn't much that can be done unfortunately.
