### ISSUE TITLE
Key binding does not work in electron(atom-shell)

### ISSUE THREAD

**Issue by foolyoghurt** [RobertWHurst/KeyboardJS#87]
In [electron](https://github.com/atom/electron), KeyboardJS will identify the running environment as **CMD**. So I must use `var KeyboardJS = require('/path/to/Keyboard.js')` to load it correctly. But then any key binding does not work.

After I change the source code to export a **global KeyboardJS** variable so I don't need to **require** it, it works.

**Comment by RobertWHurst** [comment]
KeyboardJS does not support electron, however I'm make a note to check this out and see if I can get it working.

**Comment by RobertWHurst** [comment]
Now that we're on KeyboardJS v2, and it ships with browserify's UMD wrapper, it may work for your use case. Reopen this issue if you still have issues.
