### ISSUE TITLE
Key binding error after dialog(alert...) shown

### ISSUE THREAD

**Issue by foolyoghurt** [RobertWHurst/KeyboardJS#88]
For example, as the following code shows, pressing `a` will show a alert dialog. But after that, pressing any other key will also trigger the handler to be called and show the alert dialog.

```
KeyboardJS.on('a', function() {
  alert('key a');
});
```

But the weirder is it works fine in **iframe**, here is the  [demo](http://codepen.io/foolyoghurt/pen/MwJazV) using iframe in CodePen.

**Comment by RobertWHurst** [comment]
As far as I know the issue can't be fixed. The problem is that the alert function blocks JavaScript execution. By the time the alert box is dismissed, and JavaScript resumes, the keyup event has already been missed.
