### ISSUE TITLE
How to watch and then do something with all keys...

### ISSUE THREAD

**Issue by spencerthayer** [RobertWHurst/KeyboardJS#94]
How do I pass every pressed and released key to keyboardJS?
For example:
```javascript
      keyboardJS.bind(globalKey, function(e) {
          e.preventRepeat();
          console.log(globalKey+'is pressed');
      }, function(e) {
          console.log(globalKey+'is released');
      });
```

**Comment by RobertWHurst** [comment]
You can't right now. I can add this today if you really need it. What are you trying to do?

**Comment by spencerthayer** [comment]
I'm writing a lesson for kids in juvenile detention who we teach Javascript.

It's a drum machine like an Akai that watches document for every key press and then (at the moment) makes a random sound. I figure something like this will engage them more than the typical lesson plans we have been using so far.

The problem I am having, and why I like your library, is that keydown and keypress repeat the key entry and your library is the only one that really does e.preventRepeat() correctly.

Example: http://codepen.io/spencerthayer/pen/pJZGVx

**Comment by spencerthayer** [comment]
THANKS!

**Comment by RobertWHurst** [comment]
@spencerthayer Looks slick. I like it :)

So you can now bind to any keypress by omitting the combo and just passing the handler. The keys pressed are available on the event object.

**Comment by RobertWHurst** [comment]
@spencerthayer Just a heads up, noticed a small bug. So I did another release. Use it; 2.1.1

**Comment by spencerthayer** [comment]
```javascript
    keyboardJS.bind(function(e) {
        e.preventRepeat();
        console.log(e+"is pressed");
    }, function(e) {
        console.log(e+"is released");
    });
```

The behavior isn't exactly the same as when using the original code. Instead of holding on `is pressed` it holds now on `is released`. Does that make sense?

**Comment by RobertWHurst** [comment]
Yeah, I see it too. Tests missed it. I'll patch it.
