### ISSUE TITLE
window.confirm breaks the library

### ISSUE THREAD

**Issue by Akudrevatykh** [RobertWHurst/KeyboardJS#97]
In Chrome  44.0.2403.157 m

Example:
```
import keyboardJS from 'keyboardjs';

keyboardJS.bind('a', function(e) {
  if(confirm('test'))
    console.log('a is pressed');
});
```
Steps to reproduce:
1. Press `a`
2. Press `Cancel` or hit escape
3. Any keypress will trigger the callback

**Comment by Akudrevatykh** [comment]
It appears the problem is caused by `window.confirm` blocking `keyup` event. See this fiddle for the example: http://jsfiddle.net/cg5fLja3/1/

KeyboardJS relies on `keyup` event in order to release key in `this._targetKeyUpBinding`. Sine the key is not released a consecutive keypress will contain a combo of a pressed button and matching handler. (`this.pressedKeys` in locale.js doesn't get cleaned up).

The only workaround I can think of right now is manually releasing the key after every call to confirm:

```
keyboardJS.bind('a', function(e) {
  if(confirm('test'))
    console.log('a is pressed');
  keyboardJS.releaseKey(e.keyCode);
});
```

**Comment by RobertWHurst** [comment]
Yeah, it's also true with `alert()` or any other function that blocks the event loop. I consider this out of scope for the library, but If anyone comes up with a non hacky solution to this problem I'll add it.
